### ISSUE TITLE
Speed but no Satellite Location Display Option

### ISSUE THREAD

**Issue by kd4e** [woheller69/gpscockpit#10]
I was primarily interested in the display of satellites, GPS and visible, feature of this app.
(I have it installed on a Pixel 4a with the GrapheneOS (google-purged) version of Android.)
It was non-intuitive, to me, that I needed to turn Off "GPS Lock" to view satellite data.
But that presents a list rather than a circle with linked-dots - graphically displaying the direction of satellites from current location.
Also, does your app rely on something-google or OsmAnd+ to display relative satellite location?
Thanks

**Comment by woheller69** [comment]
Showing satellite signal strength is independent from GPS lock.
But this app does not and will never show satellite positions. For this purpose you can e.g. use GPSTest from F-Droid.
