### ISSUE TITLE
IDEA: Switch to Altimeter mode

### ISSUE THREAD

**Issue by ObiSandwich** [woheller69/gpscockpit#11]
It would be cool if you had a switch to change from the current **Speedometer** mode to **Alitmeter** mode! 

This new Altimeter would show a typical aircraft altitude dial instead of the Speedometer, something like this...

![3-Pointer_Altimeter svg](https://user-images.githubusercontent.com/41534480/149464587-2d36d38f-0549-4fab-b8b7-c1a14eb8e170.png)

In this new Altimeter mode you could still have the Speed showing in the top left, just as you currently have the Altitude showing now.

`Image source: https://wikipedia.org/wiki/Altimeter`

**Comment by woheller69** [comment]
Nice idea. For the speedometer I am using a library:

https://github.com/anastr/SpeedView

I someone knows a suitable library for an altimeter I will think about it.

**Comment by woheller69** [comment]
I created a view myself. Please try. Simply remove .zip
You can swipe left/right to switch between speed and altitude view.
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7881570/app-release.apk.zip)

**Comment by ObiSandwich** [comment]
Thanks man, very slick :) Will this be on Fdroid soon?

![Screenshot_20220117-224502_1](https://user-images.githubusercontent.com/41534480/149844851-97da5c84-9e61-41d6-b3c9-53d01fc6f896.png)

**Comment by ObiSandwich** [comment]
![Screenshot_20220117-224502_1_1](https://user-images.githubusercontent.com/41534480/149845028-c4909bbe-a208-46b5-99f0-36ab8a951464.png)

**Comment by woheller69** [comment]
Changed the pointers a bit.
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7887101/app-release.apk.zip)

**Comment by KaktusXY** [comment]
Great idea, but an altimiter shows the altitude not the (ground)speed, an airspeed indicator(to be correct is not, for this usecase, perfect either because it shows the airspeed not groundspeed) would be more suitable for this.

![airspeed indicator](https://en.m.wikipedia.org/wiki/File:Airspeed_Indicator.svg)

Image source: `https://en.m.wikipedia.org/wiki/Airspeed_indicator`
