### ISSUE TITLE
change color of velocity marker

### ISSUE THREAD

**Issue by paulle** [woheller69/gpscockpit#13]
It would be to change the colour of the velocity marker from blue to yellow or orange in the dark version. Better contrast makes it easier for eyes if you have a quick glance. 
Thank you for this beautiful app.

**Comment by woheller69** [comment]
What about this?

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/8463512/app-release.apk.zip)

**Comment by paulle** [comment]
How l have to install it?

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
yes. Rename (remove .zip) and install

**Comment by paulle** [comment]
I did so, but I only get the message: app wasn't installed

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
have you tried it?

**Comment by paulle** [comment]
Yes and it's perfect with the yellow, much better contrast in the dark version.

Thank you very much for this.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
-> V1.6

**Comment by paulle** [comment]
Thank you, now it's installed.

And the yellow is much more visible than the blue one.

Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
