### ISSUE TITLE
UI cut off on low resolution device

### ISSUE THREAD

**Issue by SynthGal** [woheller69/gpscockpit#14]
Device: Figo Orbit II
Android Version: 8.1.0 (yes, it's out of date but I am using this as an offline bike computer and media player since it is nice and small instead of throwing it out)
App Version: 1.6

The app's UI is cut off on low resolution devices such as mine, which is 480 x 800. Please see screenshots. The app does not seem to respond to the phone's font size setting. It does respond to the display size setting which does solve the issue for this app, but this makes text elements too small to read in other apps. A "compact mode" for this app would be useful.

![Screenshot_20220507-071208](https://user-images.githubusercontent.com/22404684/167254725-5961dafa-1f7f-4b97-a6d0-d529f235de16.png)
![Screenshot_20220507-071502](https://user-images.githubusercontent.com/22404684/167254726-8fdc906d-692a-4996-baa8-f47ac03c93cd.png)

**Comment by woheller69** [comment]
Does not seem too bad. You should still be able to scroll

**Comment by SynthGal** [comment]
Not if both my hands are on my bike handlebars.

**Comment by woheller69** [comment]
Can you try this? I scaled down the layout for smaller devices.
Remove .zip and install (uninstall old version first)
I set the old layout for devices with min 360dp (dp=display pixel not pixel). 
So for larger devices everything should work as before.

Can you install CPU Info app and check your screen size (width in "dp") ?

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/8657631/app-release.apk.zip)

**Comment by woheller69** [comment]
Another update. Reduced the height of the ActionBar.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/8659459/app-release.apk.zip)

**Comment by SynthGal** [comment]
Apologies for the lateness of my reply, it's because of who I am as a person.

To answer your first question, 320dp x 533dp.

Here are the screenshots for the first apk.
![Screenshot_20220515-113445](https://user-images.githubusercontent.com/22404684/168484056-78d9b4cb-2a1d-484b-a973-a111dcd501d9.png)
![Screenshot_20220515-113449](https://user-images.githubusercontent.com/22404684/168484058-252d330f-ada1-4042-a4a2-d9d74b7d7e0a.png)

Here are the screenshots for the second apk.
![Screenshot_20220515-113556](https://user-images.githubusercontent.com/22404684/168484076-1eafd241-3181-480e-8fc9-e868f8fb72ee.png)
![Screenshot_20220515-113559](https://user-images.githubusercontent.com/22404684/168484077-177252f1-cd81-479a-8d1f-a6dd0b567f6f.png)

I think the reduced height of the action bar is a great solution that allows the larger text as well as being able to see all elements. Thank you so much for putting the work into this. Is there anywhere I could throw you a few bucks for it?

**Comment by woheller69** [comment]
Looks great :-)
I do not have a donation account. You can give something for charity if you like.

**Comment by woheller69** [comment]
-> V1.7
