### ISSUE TITLE
max speed is tied to speedometer's top value

### ISSUE THREAD

**Issue by CloneMMDDCVII** [woheller69/gpscockpit#16]
When travelling faster than the speedometer's needle is able to display, the number in the center of the speedometer is the max digit in the instrument view.

This means when you are going above 270mph (the highest value the speedometer could display) the speed counter remains stuck at 270mph, despite moving at faster speeds (on a plane for instance)

A better way to deal with this may be to display the gps speed instead of the speedometer's value.

**Comment by woheller69** [comment]
the speedometer is a library https://github.com/anastr/SpeedView
I do not have influence on that...

**Comment by CloneMMDDCVII** [comment]
Could add a current gps speed field down with the rest of the data ?

**Comment by woheller69** [comment]
what is the max speed you need? Is 1350 km/h enough?
I can add one more index

**Comment by woheller69** [comment]
V1.9 has another speed range up to 1350
