### ISSUE TITLE
Statistiscs data (average values) are claculated and displayed only randomly

### ISSUE THREAD

**Issue by Elmi77** [woheller69/gpscockpit#17]
Also when there is a GPS-fix, the statistics data (such as average speed, driven distance,...) are calculated and displayed only very rarely. I could not find out what causes this, for me it looks more or less random. When this error occurs, speed, latitude, longitude, compas and elapsed time are updated properly, but all other values are missing. It does not make a difference if I press the START-button or not.

Sorry for the poor quality of the image, it was made during driving in order to show the speed is working: [https://i.ibb.co/grs8Y4c/IMG-20221109-130526-DRO-1.jpg](https://i.ibb.co/grs8Y4c/IMG-20221109-130526-DRO-1.jpg)

**Comment by woheller69** [comment]
What is your  Device, OS, OS version?

I recently noticed on one of my devices that it does not correctly handle configuration changes, like change in orientation or when dark mode is switched on / off.

Please try this version, this fixed the problem on my device and is currently in test.
- uninstall old version
- remove .zip from filename
- install

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/9972973/app-release.apk.zip)

**Comment by Elmi77** [comment]
The device itself is a Android-based car-radio which does not change the orientation of the display. So the app started in landscape orientation from the very beginning - could this be a reason?

I'll check for the exact version and try the ZIP-file as soon as possible!

**Comment by woheller69** [comment]
Can you switch the debug option on? This will show a counter which is increased with every new GPS location. 
Is it reset to zero, or does the counter stay at 0?

**Comment by Elmi77** [comment]
The device runs on android 8.0.0

When turning the debug-option on, the counter stays at 0 (while speed, lat, lon and orientation are updated properly)

**Comment by woheller69** [comment]
Counting should start when Start button is pressed and the indicator on the button turn blue

**Comment by woheller69** [comment]
Have you tried the zip?

**Comment by woheller69** [comment]
what is the accuracy the GPS achieves? Displayed at the right of the coordinates.
Values are only calculated if accuracy is better than 15m.

**Comment by woheller69** [comment]
Attached is a version with 45m min accuracy. Maybe that works, but it will probably count a lot of noise.
Changes in distance are counted if they are larger than 2x GPS accuracy
Changes in altitude are only counted if they are larger than 3x GPS accuracy

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/10024293/app-release.apk.zip)

**Comment by woheller69** [comment]
did it work?

**Comment by Elmi77** [comment]
Sorry, have not tried it yet, hopefully I will find some time during next few days!

**Comment by Elmi77** [comment]
Bad news: still the same, no matter if I press "Start" or not, no statistics data are collected.

What came into my mind: that car-radio has no network connection, neither via mobile network nor via Wifi - could this be a problem?

**Comment by woheller69** [comment]
no

**Comment by woheller69** [comment]
it seems your device does not provide altitude. At the top left current altitude should be shown

**Comment by Elmi77** [comment]
The altitude is directly related to the statistics data in my case - the few times, everything worked correctly, even the altitude was shown. So, yes, it seems this could be a reason.

**Comment by Elmi77** [comment]
OK, any updates that fix this issue?

**Comment by woheller69** [comment]
an update of your bad GPS would fix it...

**Comment by Elmi77** [comment]
I tried it with different devices and different GPS-apps meanhile: it seems, a 3D fix is not always guaranteed. Means all these apps provide a lat/lon position information quite regularly but not always the height. So as this happens with other devices too, I don't think this is a problem of the GPS of this specific device. On the other hand there is no such thing like a "GPS-update" for Android...

**Comment by woheller69** [comment]
You can play with this version. For the purpose of measuring distance its sets altitude=0 regardless if there is a value or not. 
So it should not block anymore and at least count horizontal movement. But I doubt this will work great. If GPS reception is that bad that a 3D fix is not possible (which needs 4 satellites)  horizontal accuracy will also be very limited.
I cannot test that - have no device that does not get 3D fix... 
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/10167095/app-release.apk.zip)

**Comment by Elmi77** [comment]
Thanks, I'll try it and let you know! :-)

**Comment by woheller69** [comment]
Collecting of distance and average speed should also work with 3D fix.
Altitude will never be measured it is always assumed 0.

**Comment by woheller69** [comment]
just tested it. Works well with 3D fix. Accuracy must be better than 15m to start counting
