### ISSUE TITLE
HUD like view?

### ISSUE THREAD

**Issue by abdulhakam** [woheller69/gpscockpit#18]
Will it be possible to view all this in flipped so it can be put on dashboard and see its reflection on windscreen similar to HUDway? 

thanks.

**Comment by woheller69** [comment]
Unfortunately no. You asked this a year ago already. See #4

**Comment by woheller69** [comment]
Actually it seems to be quite simple.

Please try this. 
-Uninstall old version.
-Remove .zip from filename
-Install


[app-release_HUD.apk.zip](https://github.com/woheller69/gpscockpit/files/10104274/app-release_HUD.apk.zip)

**Comment by woheller69** [comment]
-> V2.1
