### ISSUE TITLE
Share link uses google

### ISSUE THREAD

**Issue by gdt** [woheller69/gpscockpit#2]
This has two problems:

 *  google is a data-gathering company, and an app that promises no tracking should not suggest to share a link which will cause the location to be sent to google

  * relative to f-droid, google is a NonFree network service

A suggestion is instead to use one of:
  * a geo: URI
  * a link via openstreetmap

**Comment by woheller69** [comment]
The app is not sending data to google. It is just sending a link with a URL which allows the receiver to open the link in google maps which is available on most devices. If the receiver does not want to use google he can just use the coordinates in the link.
Or you as the sender can use the copy button in the app and then paste the coordinates where you like, e.g in OSMAND.

**Comment by gdt** [comment]
Sorry, I didn't mean to imply that the app *directly* sends data.

The point is that when the receiver uses the link it will send the location to google, and I don't think that's a good thing to encourage.    The README doesn't hint that there's a google link in share, only "Location coordinates can be copied to clipboard, shared, or opened in a maps app,".

**Comment by woheller69** [comment]
Will be replaced with OpenStreetMap link in next release

**Comment by gdt** [comment]
Great - thanks for listening and adjusting.
