### ISSUE TITLE
Locking frequency(?) too low

### ISSUE THREAD

**Issue by Obikawa** [woheller69/gpscockpit#20]
Hello.

I use the application to keep GPS locked in the background, and it does the job very well.

There is one minor annoyance that I recently uncovered, when I decided to have all the system icons enabled.  The location pin constantly shows and hides, when the GPS is not in the foreground.

Am I right to think that the GPS lock is maintained by polling the device every couple of seconds?  In which case the annoyance could worked around by polling more often.

**Comment by woheller69** [comment]
No, there is no locking frequency

**Comment by Obikawa** [comment]
So is there no hope for an icon that just stays on?

**Comment by woheller69** [comment]
Do you need a location update faster than every few seconds?

**Comment by Obikawa** [comment]
No - I am simply annoyed at the icon behaviour.  My reasoning is that a "locked GPS" is an ongoing state, so why is the icon in a transient state?

I admit - the title is not accurate.  But I was not able to come up with anything better quickly.

**Comment by woheller69** [comment]
the icon is shown when an app requests a location update.
The locationListener is locked nevertheless

**Comment by Obikawa** [comment]
Sounds to me like a bug in the icon design.

I am just a user of Android.  Is the "locationListener" involved in every interaction with GPS?  If yes, then in my opinion the icon state should represent the state of the "locationListener", not whatever any program wants in a moment.

With that said, I am letting go of this.  I decided to disable the icon.  I don't think I have any power as a single user to change the upstream's design.

**Comment by woheller69** [comment]
https://android.stackexchange.com/questions/43101/gps-and-icons-on-the-android-notification-bar#43104
