### ISSUE TITLE
Soft-Stop at the SpeedLimit

### ISSUE THREAD

**Issue by Kutabu** [woheller69/gpscockpit#23]
I assume you speak german, therefore the german version below:

I noticed that the speed limiter does not only refer to the graphic display, but also to the numerical value. When the limit of 27 km/h is reached, the pointer stops at 27 km/h and the numerical display also stops. I think it makes sense if at least the value displayed as digits also runs outside the limiter.

Can this be solved in the app or would it have to be adapted in the resource anastr/SpeedView?

Alternatives:
1. when the speed limit is exceeded, the app switches to the next higher predefined value (and maybe back again).
2. you can set your own speed limit in the settings. This should be possible via an additional "custom value" in the speedList (I will open a separate issue for this).

__________________________________________________________________________________
**In German:**
Mir ist aufgefallen, dass der Speed-Limiter sich nicht nur auf die grafische Anzeige bezieht, sondern auch auf den numerischen Wert. D.h. wenn das Limit von 27 km/h überschritten wird, bleibt der Zeiger bei 27 km/h stehen. Aber auch die Nummernanzeige geht dann nicht über 27 km/h hinaus. Ich halte es für sinnvoll, wenn zumindest der als Ziffern angezeigte Wert auch über den Limiter hinausläuft.

Ist das in der App zu lösen oder müsste man das in der Resource anastr/SpeedView anpassen?

Alternativen:
1. Beim Überschreiten des Speedlimits wechselt die App auf den nächst höheren vordefinierten Wert (und vielleicht dann wieder zurück).
2. Man kann in den Einstellungen einen eigenen Speed-Limit festlegen. Das sollte über einen zusätzlichen "custom Value" in der speedList möglich sein (ich mache dafür nochmal einen eigenen Issue auf).

**Comment by woheller69** [comment]
Has to be fixed in SpeedView
Duplicate #16

**Comment by Kutabu** [comment]
Sorry, I didn´t searched the closed issues. Thanks.
