### ISSUE TITLE
Custom SpeedLimit & Help

### ISSUE THREAD

**Issue by Kutabu** [woheller69/gpscockpit#24]
There is a list of predefined speed limits in the app. I suggest creating the possibility of a custom value in the settings.

Furthermore, it took me a long time to find out that the limit can be changed by clicking on the display. Here a minimal help file in the setting would be useful (or a hint under "about").

**Comment by woheller69** [comment]
Help is in "About" and F-Droid description.
A custom value causes other issues with SpeedView

**Comment by woheller69** [comment]
Help is in "About" and F-Droid description.
A custom value causes other issues with SpeedView

**Comment by woheller69** [comment]
"Speed range can be selected by clicking on the speedometer. "

**Comment by Kutabu** [comment]
I assume with other issues you mean, that the limit should be a multiple of 9, because of the SpeedView markers. I this, this can easily be solved... but this is our app and you can decide the features.

Help is not displayed in "About" within my app. But there is indeed the link to GitHub and F-Droid. Anyway, because of the missing hint, I haven´t searched this pages for help.

Thanks for the quick response.
