### ISSUE TITLE
Enhancement Request: show position data in other formats

### ISSUE THREAD

**Issue by jp-coding** [woheller69/gpscockpit#25]
Please add an option to display the position not only in decimal notation but also in DMS as nautical charts and plotters use it.
So an option to display 40°42'51" N, 74°0'21" W rather than 40.714, -74.006 would be great.

**Comment by woheller69** [comment]
will think about it. Should that format always be used in nautical mode or should it be a separate option?

**Comment by woheller69** [comment]
For a first test I implemented it for nautical mode. Unfortunately this format requires more space so I had to scale the text.

Uninstall
Remove.zip and install

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/11965368/app-release.apk.zip)

**Comment by woheller69** [comment]
Another update: Reduced display of seconds to 0.1" to save some space
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/11975370/app-release.apk.zip)

**Comment by woheller69** [comment]
Better solution without changing text size
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/11990293/app-release.apk.zip)
