### ISSUE TITLE
Wrong language code

### ISSUE THREAD

**Issue by FTno** [woheller69/gpscockpit#26]
Refer to pull request https://github.com/woheller69/gpscockpit/commit/67625cb5b14b41d11669a7449569f58c3fb47032

Just installed V2.3 and the translated strings from the pull request are not displayed (strings are in english).
After decompiling the apk file I see that there are both a values-no and a values-nb folder which contain translations from different sources, with values-no containing the referred pull request.
This puzzled me, but I now see that the language code of the pull request has been changed from 'nb' to 'no', and I'm pretty sure this is the problem so please change it back to 'nb'.

I see that one new string has been added recently to the norwegian language file:  `<string name="turned_on">En</string>` (the english source: `<string name="turned_on">On</string>`)
This should be a correct translation: `<string name="turned_on">På</string>`

By the way, I have also made a pull request for the compassview: https://github.com/woheller69/CompassView/pull/1

**Comment by woheller69** [comment]
For Norwegian the code should be 'no' as far as I understand

**Comment by woheller69** [comment]
Or should I use the strings for both, no and nb?

**Comment by FTno** [comment]
Most apps I have seen uses values-nb (or values-nb-rNO). values-no doesn't work on phones I have tried, but on the other hand  it shouldn't harm to have both folders with duplicate content.

**Comment by woheller69** [comment]
Then I will put the content in nb and no folders.
Will also do this for your compassview PR.
Sorry I did not receive a notification for this PR.

**Comment by woheller69** [comment]
Please try. CompassView  is also merged and strings are in values-nb and values-no

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/11994616/app-release.apk.zip)

**Comment by FTno** [comment]
The test version displays the norwegian strings fine (compassview too). Thanks!
