### ISSUE TITLE
F-Droid won't install

### ISSUE THREAD

**Issue by Noitarud** [woheller69/gpscockpit#29]
Gives "not installed" error.

I did have it (I presume had very old version) in but today removed it, since apk is not supplied by author in Git but did find v1.3 in one of its issues, installed, F droid then sees it as installed, uninstalled in F droid, tried install again and same error. Not sure when/what I installed initially (log?).
Android 10

**Comment by woheller69** [comment]
App from F-Droid installs fine. The debug versions from GitHub are signed with different key. You need to uninstall first. Maybe reboot your device

**Comment by Noitarud** [comment]
Id send a video but Github has stopped taking uploads from my browser. 
All FD shows is a little message at the bottom "app not installed".
Your Git hub versions have only •"source code (zip)" or •"source code(tar.gz)" i do not know what to do with these, and i do not know how to obtain your apk or your debug apks from your Git hub unless you upload them alongside the source files for users to download them **[here](https://github.com/woheller69/gpscockpit/releases)** as most other developers do in their projects, if they are there I cannot see them (each one says two assets, the files already said). The only way i can use your app right now is through issue nine which has a debug zip uploaded. If you had all the apks uploaded i would be able to tell you which version cannot install (if i keep persuing you on this).

In the case of DuckDuckGo, i have two apks from them,
•Duckduckgo-5.145.5-play-release.apk
•Com.duckduckgo.mobile.android_51454000.apk
When i install from GhostCommander, The Play one failed with a message in the middle of screen saying the same message as yours…

**Comment by woheller69** [comment]
just remove .zip from my apks on Github

**Comment by Noitarud** [comment]
Okay, i downloaded a few zips, and (to be sure) I first tried gpscockpit-1.7.zip renamed to gpscockpit-1.7.apk acquired from the link that says "**Source** code(zip)  May 17, 2022" and the message I get is "there was a problem while parsing the package". I still think its not the same…

**Comment by woheller69** [comment]
have you ckecked in Android settings if the app is really uninstalled?

And maybe try another app for installing, e.g. TotalCommander

**Comment by Noitarud** [comment]
in Ghost commander, issue nine's apk has the GPS app's icon (as all the other app's apks i have, have their icons from their developers) but the source code zips i downloaded and renamed have a green droid on a page.

(Reinstalled working apk)
Settings/apps/see all apps/Gps cockpit/

**Comment by woheller69** [comment]
does it work now?

**Comment by Noitarud** [comment]
The renamed source zip does the same thing. It is true APKs are zip files, but the content is different.

Debug apk folders root dir: _Kotlin, META-INF, res_
Debug apk files of root dir: _AndroidManifest.xml, build-data.properties, classes.dex, classes2.dex, resources.arsc_

Source zip has only folder "gpscockpit-1.7" in its root dir, listing contents:
Source zip folders in only dir: _app, fastlane, gradle_
Source zip files of only dir: _.gitignore build.gradle gradle.properties gradlew gradlew.bat LICENCE README.md settings.gradle_

**Comment by woheller69** [comment]
these old versions are already deleted on F-Droid, they only keep the last 3 versions, so min 2.3
