### ISSUE TITLE
compass don't work

### ISSUE THREAD

**Issue by paulle** [woheller69/gpscockpit#3]
The compass don't work. The compass scale is always grey, no blue as in the screenshot on f-droid and showing north in every position.
Android 11
Sony Xperia 4

**Comment by woheller69** [comment]
Then your GPS position is not good enough and does not provide data on direction (bearing).


    if (mGpsLocation.hasBearing()) {
            mB.gpsCont.compass.setLineColor(ContextCompat.getColor(this,R.color.accent));
            mB.gpsCont.compass.setTextColor(ContextCompat.getColor(this,R.color.dynamicFgDim));
            mB.gpsCont.compass.setShowMarker(true);
            bearing = mGpsLocation.getBearing();
          } else {
            mB.gpsCont.compass.setLineColor(ContextCompat.getColor(this,R.color.disabledStateColor));
            mB.gpsCont.compass.setTextColor(ContextCompat.getColor(this,R.color.disabledStateColor));
            mB.gpsCont.compass.setShowMarker(false);
          }

**Comment by paulle** [comment]
Thank you very much for the hint. And yes compass is working with a better GPS fix.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
