### ISSUE TITLE
wrong speeds shown (limited speed value and avg > max)

### ISSUE THREAD

**Issue by yellow-submarine-on-tour** [woheller69/gpscockpit#31]
Hi,

first of all, thanks for the great app. Most of all, that its without tracking and ads.

Today I was flying in an airplane and used GPS Cockpit because I was curios how high amd how fast we are flying. Hereby:
- The shown speed value (number) is also limited with the max value of the gauge. In my opinion the number should always show the actual speed. 
- The max value was smaller than the average value which cannot be true (max 823 km/h, avg 1048 km/h)

Best wisthes
Christian

**Comment by yellow-submarine-on-tour** [comment]
![Screenshot_20230907-162815_GPS Cockpit](https://github.com/woheller69/gpscockpit/assets/32867340/de4a07b1-e0a8-43ed-9010-39d1bdaada1f)

**Comment by woheller69** [comment]
See #16 #23

**Comment by yellow-submarine-on-tour** [comment]
Sorry, should have had also a look to the closed issues, not only the open ones...

Beside the limited value in the SpeedView-lib, what about the issue, that the average value is greater than the max value? This cannot be true

**Comment by woheller69** [comment]
Average is calculated from real GPS speed.
Click on Speedometer to increase range
