### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by Quantum-Future** [woheller69/gpscockpit#36]
Great app !

I have a suggestion:  Can you add a button for auto-starting when the vehicle moves?
When the user press this button, a message is displayed "Waiting for motion" (or similar). When vehicle moves, the message disappears and starts counting distance and time, and calculating average speed, etc.
The detection of initial motion could be done by using accelerometer instead of GPS to be more precise.

**Comment by woheller69** [comment]
I do not plan to implement this
