### ISSUE TITLE
Installs but no launch tile

### ISSUE THREAD

**Issue by BentonH** [woheller69/gpscockpit#38]
Using a Pixel 4a, w/ Android v 13.
Installed GPS Cockpit latest, v 2.6.

The app installed and runs fine, except it didn't put a launch tile, whatever it's called, anywhere I can find on the app launch pages.  The only way I've been able to start it is by going to the f-droid store/installer and launching from there.

Benton 24jul24

**Comment by woheller69** [comment]
Then that is a bug in your launcher. Nothing I can change...
