### ISSUE TITLE
flipped view so it can be used as a HUD.

### ISSUE THREAD

**Issue by abdulhakam** [woheller69/gpscockpit#4]
flip

**Comment by woheller69** [comment]
What do you mean?

**Comment by woheller69** [comment]
Head up display? I don't think this is possible with the used libraries

**Comment by abdulhakam** [comment]
I meant there was a very old  HUD app on f-droid, it viewed the gps speed as flipped text, so it would be an extra feature for the app I think.

**Comment by woheller69** [comment]
for sure it is theoretically possible. But I am using libraries and do not draw the pixels on my own. And with these libs it is not possible...
