### ISSUE TITLE
Deep sleep inhibited if GPS is disabled

### ISSUE THREAD

**Issue by Mrnofish** [woheller69/gpscockpit#41]
1. Press Start
2. Disable Location manually or otherwise

The app prevents the system from entering Deep Sleep.

It's OK for the app to keep running in background but forcing the device to stay awake until the userr presses stop is a big no-no.

**Comment by woheller69** [comment]
Non-sense. The app needs your location every few seconds. There is no time for deep sleep. Just uninstall it.
