### ISSUE TITLE
second tab with average velocity

### ISSUE THREAD

**Issue by paulle** [woheller69/gpscockpit#5]
First thank you for this nice app.
What do you think about a second tab showing average speed and two graphs, speed over time and altitude over time.

**Comment by woheller69** [comment]
This would require to make this a tracking app, because you need to store all positions over time to calculate that.
I think such a feature should rather be built on top of a GPS tracking app.

**Comment by paulle** [comment]
I would like to see it in your app, but I don't know how much work is this, because I've no coding skills. And you are right one is looking mostly looking at the actual speed and velocity.

But another idea what do you think of a button to change the tachometer scale. As it is, and the button to change it for 0-40 km/h. For running, biking, walking.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
an option to change range for slow speeds should be possible. Will think about it

**Comment by paulle** [comment]
Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
Please try. You can change the speed range by clicking ton the speedometer.

Rename to .apk (simply remove .zip)

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7696626/app-release.apk.zip)

**Comment by paulle** [comment]
Thank you very much, yes it works, now I can change the speed range. Please can you add maybe one range more from

0-20 or 25 km/h.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
Here you go.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7697072/app-release.apk.zip)

**Comment by paulle** [comment]
WOW, really fast. Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
Installed and working. Thank you very much.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
Maybe you want to try this version.
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7727498/app-release.apk.zip)

When the START button is pressed travel distance is recorded (horizontal movement and also
accumulated up and down movements). A change is only recognized and added to the distance if
the position changes by more than 2x GPS accuracy for horizontal movement and 3x GPS accuracy for
vertical movements and only if accuracy is at least 15m.

At the moment there is also a counter which is increased every time a new location is received.
This is for debug purposes only, in order to see if the app freezes due to power management. See below.
Later this counter will be removed and average speed can be displayed instead.

Depending on the device this may or may not work with screen off. 
Some manufacturers have implemented hostile energy management options and do not respect
app permissions for holding wake locks or ignore battery optimizations.

See https://dontkillmyapp.com/

As an example this works very well with my phone based on LineageOS and does not work well with my 
Samsung tablet. There after maybe 30min with screen off the app stops measuring distance.

**Comment by paulle** [comment]
Thank you, seems very promising. Will try it next, because just now I'm sick and in bed.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
Installed without problems, looks fine so far, but I've to wait till I can go out, for more testing.

Sony Xperia 5, android11

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
I tried the app today, working fine. Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
does it also work with screen off or even in background for a longer period of time (> 1h)? 
There should be about 1800 counts per hour. 
(Location should roughly update every 2 seconds)

**Comment by paulle** [comment]
Didn't try it. Will try it next week.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
Another update. Added average speed and max speed.
The counter for debug purpose is now at the top. Will be removed in future.

Should be quite close to a release now :-)

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7739157/app-release.apk.zip)

**Comment by paulle** [comment]
I tried you app about two hours, in this time I went by bus, walking and inside shops an a café there is no gnss signal.

But everything seems to work fine. It's a great little app.

Very good work. And much better because it's open source.

Thank you

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
And the app is working in the background too. Tested one hour.

**Comment by woheller69** [comment]
Great. Here comes another update which might is a release candidate.
[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7741220/app-release.apk.zip)

**Comment by paulle** [comment]
Installed, will test tomorrow

**Comment by woheller69** [comment]
Another final (?) change: Different layout for landscape orientation.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7744682/app-release.apk.zip)

**Comment by paulle** [comment]
![Screenshot_20211220-125440](https://user-images.githubusercontent.com/4852079/146763643-eb3dd984-fad0-43c4-ab4a-76176c2f0f50.png)
Landscape is fine

**Comment by woheller69** [comment]
On my phone the 0.0 and START button are also visible in landscape mode but that of course depends on the aspect ratio.
When testing please also change orientation while tracking distance and altitude up/down to see if orientation changes are handled correctly. But as far as I can see so far everything works fine. On large tablets the layout is still not great but this is something for the future. Maybe there is a layout expert around who wants to help...

**Comment by paulle** [comment]
Maybe it is because I've a Sony phone, they all have 21:9 ratio,

In my case 1080x2520 px

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
I've to slide a little bit the display for making the start bottom visible.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by paulle** [comment]
![Screenshot_20211220-133903](https://user-images.githubusercontent.com/4852079/146768590-4d0d0cd9-c7a7-4c60-9a00-e61cab1384ff.png)

**Comment by woheller69** [comment]
Another update. Had to fix a bug when phone orientation was changed while app running in background.
In this case the debug counter - and of course all other values - resumed with the state when sent to background.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7746132/app-release.apk.zip)

**Comment by woheller69** [comment]
Some more fixes. Values were reset when switching between day / night mode (also when done automatically by system

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7761309/app-release.apk.zip)
)

**Comment by paulle** [comment]
Installed

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by woheller69** [comment]
Released V1.3
