### ISSUE TITLE
Option to show speed in knots and heading in degrees

### ISSUE THREAD

**Issue by KaktusXY** [woheller69/gpscockpit#8]

**Comment by woheller69** [comment]
speed in knots should be ok, the compassView library I am using only supports N, NW, etc

**Comment by woheller69** [comment]
Please try this. This is how I could modify the external library to show degrees instead of N, NW, etc.
It does not yet show knots.

Just remove ".zip" and install.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7776665/app-release.apk.zip)

**Comment by woheller69** [comment]
Another update. Thicker lines for 5 degree steps.
(degrees are only shown in portrait view in this version)

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7776751/app-release.apk.zip)

**Comment by woheller69** [comment]
Now including options for knots and compass in degrees.
Please test and let me know if it works as expected.
Just remove ".zip" and install.

[app-release.apk.zip](https://github.com/woheller69/gpscockpit/files/7781210/app-release.apk.zip)
